apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-deployment
  labels:
    app: nginix

# Spec for Deployment
spec:
  replicas: 10
  selector:
    matchLabels:
       app: nginix

# POD Template SPEC
  template:
    metadata:
      labels:
        app: nginix
    spec:
      containers:
        - name: webserver
          image: myrepos28/static_page
          ports:
          - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginix
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80